[2025-03-19T08:04:42.099+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-19T08:04:42.117+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: github_etl.load manual__2025-03-19T08:04:23.353688+00:00 [queued]>
[2025-03-19T08:04:42.123+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: github_etl.load manual__2025-03-19T08:04:23.353688+00:00 [queued]>
[2025-03-19T08:04:42.123+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-03-19T08:04:42.260+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2025-03-19 08:04:23.353688+00:00
[2025-03-19T08:04:42.276+0000] {standard_task_runner.py:63} INFO - Started process 4661 to run task
[2025-03-19T08:04:42.279+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'github_etl', 'load', 'manual__2025-03-19T08:04:23.353688+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/github_etl.py', '--cfg-path', '/tmp/tmpb4v737wx']
[2025-03-19T08:04:42.281+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask load
[2025-03-19T08:04:42.315+0000] {task_command.py:426} INFO - Running <TaskInstance: github_etl.load manual__2025-03-19T08:04:23.353688+00:00 [running]> on host 09bb9170f096
[2025-03-19T08:04:42.450+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='github_etl' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T08:04:23.353688+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T08:04:23.353688+00:00'
[2025-03-19T08:04:42.451+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-19T08:04:43.263+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-03-19T08:04:43.265+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-19T08:04:43.273+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=github_etl, task_id=load, run_id=manual__2025-03-19T08:04:23.353688+00:00, execution_date=20250319T080423, start_date=20250319T080442, end_date=20250319T080443
[2025-03-19T08:04:43.360+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-19T08:04:43.376+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T08:04:43.381+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
